include: package:flutter_lints/flutter.yaml

linter:
  rules:
    non_constant_identifier_names: false
    omit_local_variable_types: false
    unawaited_futures: false
    unnecessary_getters_setters: false
    avoid_function_literals_in_foreach_calls: false
    use_key_in_widget_constructors: false
    prefer_const_constructors: false
    constant_identifier_names: false
    prefer_const_constructors_in_immutables: false
    sized_box_for_whitespace: false
    prefer_const_literals_to_create_immutables: false